version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - ../database/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWOR}
